### ISSUE TITLE
'FATAL: Error inserting nvidia_current ...: No such device.' ASUS 1215N

### ISSUE THREAD

**Issue by DrJohn999** [MrMEEE/ironhide#41]
Ubuntu 11.04 on Asus 1215N. Completely removed Bumblebee (purged), installed Ironhide from the ppa. Caught the latest updates, ran ironhide-configuration, which was unable to run the glxgears tests.
xorg.conf.nvidia has "ConnectedMonitor"  "DFP-0", which at one time worked in Bumblebee.
Now, enable/disablecard works OK, but not optirun:

```myself@eee-1215N:~$ optirun glxgears
- Starting Ironhide X server ironhide                                          Enabled nVidia card
  FATAL: Error inserting nvidia_current (/lib/modules/2.6.38-11-generic/updates/dkms/nvidia-current.ko): No such device
  ... \* The nvidia driver was not loaded and the nouveau module should be deactivated                                                                              \* Try: sudo rmmod nouveau && sudo modprobe nvidia-current                       \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log[fail] 
  ironhide could not be started - optirun cannot be executed.
  myself@eee-1215N:~$ ironhide-disablecard
  ERROR: Module nvidia does not exist in /proc/modules
  Disabled nVidia card
  myself@eee-1215N:~$ `
  Running
  `sudo rmmod nouveau && sudo modprobe nvidia-current

```
hangs the system, have to reboot. 

The situation is, as far as I can tell, unchanged from the last Bumblebee, on this PC. Any suggestions greatly appreciated.

```

**Comment by MrMEEE** [comment]
Please try newest version...

If that doesn't work please try:

running the ironhide-settings utility and change "Always enable the nVidia card before disabling" to 0/no... and the reboot

**Comment by DrJohn999** [comment]
Hello,

Newest version installed via updates; ironhide-configuration as auto-ran during the update was successful, and glxgears ran on the nVidia graphics. I then ran ironhide-disablecard, which failed. After that, otpirun glxgears failed in the same manner as shown in the first comment above.

With ironhide-settings, changed "Always Enable the nVidia card..." to 0, rebooted, but no difference.

Re-ran ironhide-configuration, and now it failed to set up the card (no glxgears), and it reported it had not set up the power settings. However, now enable/disable-card runs just fine...

All in all, I'm back to exactly where I started, again.

**Comment by DrJohn999** [comment]
Sorry, hit the Comment and Close button by mistake

**Comment by MrMEEE** [comment]
Please try to update to version -ubuntu35 .. it should be available within the hour.. made a bug...

**Comment by DrJohn999** [comment]
Update was to -ubuntu36.
Configuration ran OK inside the update, but:
``` username@eee-1215N:~$ optirun glxgears
- Starting Ironhide X server ironhide                                          Ironhide hasn't been configured for power management, please run ironhide-configuration.
  .                                                                        [ OK ]
  - Stopping Ironhide X server ironhide                                   [fail] `
    Ran ironhide-configuration:
    `username@eee-1215N:~$ sudo ironhide-configuration
    [sudo] password for username: 
    1
    AUTO
    Disabled nVidia card
  - Starting Ironhide X server ironhide                                          Ironhide hasn't been configured for power management, please run ironhide-configuration.
    ... \* The nvidia driver was not loaded and the nouveau module should be deactivated                                                                              \* Try: sudo rmmod nouveau && sudo modprobe nvidia-current                       \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log[fail] 
  - Stopping Ironhide X server ironhide                                   [fail] 
  - Starting Ironhide X server ironhide                                          Enabled nVidia card
    ... \* The nvidia driver was not loaded and the nouveau module should be deactivated                                                                              \* Try: sudo rmmod nouveau && sudo modprobe nvidia-current                       \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log[fail] 
  - Stopping Ironhide X server ironhide                                   [fail] 
    System start/stop links for /etc/init.d/ironhide already exist.
    Adding user username to group ironhide
    username@eee-1215N:~$  ```
    In the graphical UI for ironhide-configuration, Ichoose configuration #4, xv option. Old enable/disable scripts detected and copied, but the "initial tests failed" and "Power Configuration tests failed"
    Now rebooting, will comment more in a moment.

**Comment by DrJohn999** [comment]
First (before reboot) here is /var/log/Xorg.8.log:
`[  9687.259] 
X.Org X Server 1.10.1
Release Date: 2011-04-15
[  9687.259] X Protocol Version 11, Revision 0
[  9687.259] Build Operating System: Linux 2.6.24-29-server i686 Ubuntu
[  9687.259] Current Operating System: Linux eee-1215N 2.6.38-11-generic #48-Ubuntu SMP Fri Jul 29 19:05:14 UTC 2011 i686
[  9687.259] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-2.6.38-11-generic root=UUID=63b5d4b7-d4ab-4930-9101-f97573f8803c ro quiet splash vt.handoff=7
[  9687.259] Build Date: 11 August 2011  03:47:56PM
[  9687.259] xorg-server 2:1.10.1-1ubuntu1.2 (For technical support please see http://www.ubuntu.com/support) 
[  9687.259] Current version of pixman: 0.20.2
[  9687.259]    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
[  9687.259] Markers: (--) probed, (**) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  9687.259] (==) Log file: "/var/log/Xorg.8.log", Time: Wed Sep  7 16:25:06 2011
[  9687.260] (++) Using config file: "/etc/X11/xorg.conf.nvidia"
[  9687.260] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  9687.261] (==) ServerLayout "Layout0"
[  9687.261] (**) |-->Screen "Screen0" (0)
[  9687.261] (**) |   |-->Monitor "Monitor0"
[  9687.262] (**) |   |-->Device "Device0"
[  9687.262] (**) Option "AutoAddDevices" "false"
[  9687.262] (**) Not automatically adding devices
[  9687.262] (==) Automatically enabling devices
[  9687.262] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  9687.262]    Entry deleted from font path.
[  9687.262] (==) FontPath set to:
    /usr/share/fonts/X11/misc,
    /usr/share/fonts/X11/100dpi/:unscaled,
    /usr/share/fonts/X11/75dpi/:unscaled,
    /usr/share/fonts/X11/Type1,
    /usr/share/fonts/X11/100dpi,
    /usr/share/fonts/X11/75dpi,
    /var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType,
    built-ins
[  9687.262] (++) ModulePath set to "/usr/lib/nvidia-current/xorg,/usr/lib/xorg/modules"
[  9687.262] (**) Extension "Composite" is enabled
[  9687.262] (==) |-->Input Device "<default pointer>"
[  9687.263] (==) |-->Input Device "<default keyboard>"
[  9687.263] (==) The core pointer device wasn't specified explicitly in the layout.
    Using the default mouse configuration.
[  9687.263] (==) The core keyboard device wasn't specified explicitly in the layout.
    Using the default keyboard configuration.
[  9687.263] (II) Loader magic: 0x81ffde0
[  9687.263] (II) Module ABI versions:
[  9687.263]    X.Org ANSI C Emulation: 0.4
[  9687.263]    X.Org Video Driver: 10.0
[  9687.263]    X.Org XInput driver : 12.3
[  9687.263]    X.Org Server Extension : 5.0
[  9687.265] (--) PCI:*(0:0:2:0) 8086:a001:1043:8446 rev 2, Mem @ 0xf5e00000/524288, 0xb0000000/268435456, 0xf5d00000/1048576, I/O @ 0x0000cc00/8
[  9687.265] (--) PCI: (0:0:2:1) 8086:a002:1043:8446 rev 2, Mem @ 0xf5e80000/524288
[  9687.265] (--) PCI: (0:4:0:0) 10de:0a76:1043:8446 rev 162, Mem @ 0xfa000000/16777216, 0xd0000000/268435456, 0xce000000/33554432, I/O @ 0x0000ec00/128, BIOS @ 0x????????/524288
[  9687.265] (II) Open ACPI successful (/var/run/acpid.socket)
[  9687.265] (II) "extmod" will be loaded. This was enabled by default and also specified in the config file.
[  9687.265] (II) "dbe" will be loaded. This was enabled by default and also specified in the config file.
[  9687.265] (II) "glx" will be loaded. This was enabled by default and also specified in the config file.
[  9687.265] (II) "record" will be loaded. This was enabled by default and also specified in the config file.
[  9687.266] (II) "dri" will be loaded by default.
[  9687.266] (II) "dri2" will be loaded by default.
[  9687.266] (II) LoadModule: "dbe"
[  9687.267] (II) Loading /usr/lib/xorg/modules/extensions/libdbe.so
[  9687.267] (II) Module dbe: vendor="X.Org Foundation"
[  9687.267]    compiled for 1.10.1, module version = 1.0.0
[  9687.267]    Module class: X.Org Server Extension
[  9687.267]    ABI class: X.Org Server Extension, version 5.0
[  9687.267] (II) Loading extension DOUBLE-BUFFER
[  9687.267] (II) LoadModule: "extmod"
[  9687.267] (II) Loading /usr/lib/xorg/modules/extensions/libextmod.so
[  9687.268] (II) Module extmod: vendor="X.Org Foundation"
[  9687.268]    compiled for 1.10.1, module version = 1.0.0
[  9687.268]    Module class: X.Org Server Extension
[  9687.268]    ABI class: X.Org Server Extension, version 5.0
[  9687.268] (II) Loading extension MIT-SCREEN-SAVER
[  9687.268] (II) Loading extension XFree86-VidModeExtension
[  9687.268] (II) Loading extension XFree86-DGA
[  9687.268] (II) Loading extension DPMS
[  9687.268] (II) Loading extension XVideo
[  9687.268] (II) Loading extension XVideo-MotionCompensation
[  9687.268] (II) Loading extension X-Resource
[  9687.268] (II) LoadModule: "glx"
[  9687.268] (II) Loading /usr/lib/nvidia-current/xorg/libglx.so
[  9687.307] (II) Module glx: vendor="NVIDIA Corporation"
[  9687.307]    compiled for 4.0.2, module version = 1.0.0
[  9687.307]    Module class: X.Org Server Extension
[  9687.307] (II) NVIDIA GLX Module  280.04  Fri Jun 24 11:58:01 PDT 2011
[  9687.307] (II) Loading extension GLX
[  9687.307] (II) LoadModule: "record"
[  9687.307] (II) Loading /usr/lib/xorg/modules/extensions/librecord.so
[  9687.308] (II) Module record: vendor="X.Org Foundation"
[  9687.308]    compiled for 1.10.1, module version = 1.13.0
[  9687.308]    Module class: X.Org Server Extension
[  9687.308]    ABI class: X.Org Server Extension, version 5.0
[  9687.308] (II) Loading extension RECORD
[  9687.308] (II) LoadModule: "dri"
[  9687.308] (II) Loading /usr/lib/xorg/modules/extensions/libdri.so
[  9687.309] (II) Module dri: vendor="X.Org Foundation"
[  9687.309]    compiled for 1.10.1, module version = 1.0.0
[  9687.309]    ABI class: X.Org Server Extension, version 5.0
[  9687.309] (II) Loading extension XFree86-DRI
[  9687.309] (II) LoadModule: "dri2"
[  9687.309] (II) Loading /usr/lib/xorg/modules/extensions/libdri2.so
[  9687.310] (II) Module dri2: vendor="X.Org Foundation"
[  9687.310]    compiled for 1.10.1, module version = 1.2.0
[  9687.310]    ABI class: X.Org Server Extension, version 5.0
[  9687.310] (II) Loading extension DRI2
[  9687.310] (II) LoadModule: "nvidia"
[  9687.310] (II) Loading /usr/lib/nvidia-current/xorg/nvidia_drv.so
[  9687.311] (II) Module nvidia: vendor="NVIDIA Corporation"
[  9687.311]    compiled for 4.0.2, module version = 1.0.0
[  9687.311]    Module class: X.Org Video Driver
[  9687.318] (EE) NVIDIA: Failed to load the NVIDIA kernel module. Please check your
[  9687.318] (EE) NVIDIA:     system's kernel log for additional error messages.
[  9687.318] (II) UnloadModule: "nvidia"
[  9687.318] (II) Unloading nvidia
[  9687.318] (EE) Failed to load module "nvidia" (module-specific error, 0)
[  9687.318] (II) LoadModule: "mouse"
[  9687.319] (II) Loading /usr/lib/xorg/modules/input/mouse_drv.so
[  9687.319] (II) Module mouse: vendor="X.Org Foundation"
[  9687.319]    compiled for 1.9.99.902, module version = 1.6.99
[  9687.319]    Module class: X.Org XInput Driver
[  9687.319]    ABI class: X.Org XInput driver, version 12.3
[  9687.319] (II) LoadModule: "kbd"
[  9687.321] (WW) Warning, couldn't open module kbd
[  9687.322] (II) UnloadModule: "kbd"
[  9687.322] (II) Unloading kbd
[  9687.322] (EE) Failed to load module "kbd" (module does not exist, 0)
[  9687.322] (EE) No drivers available.
[  9687.322] 
Fatal server error:
[  9687.322] no screens found
[  9687.322] 
Please consult the The X.Org Foundation support 
     at http://wiki.x.org
 for help. 
[  9687.322] Please also check the log file at "/var/log/Xorg.8.log" for additional information.
[  9687.322]`
and dmesg:
`[ 9345.398670] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PSC
[ 9345.398696] acpi_call: Call successful: 0x3
[ 9345.402751] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PS0
[ 9345.644909] acpi_call: Call successful: 0x0
[ 9345.649061] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PSC
[ 9345.649087] acpi_call: Call successful: 0x0
[ 9346.152736] nvidia: module license 'NVIDIA' taints kernel.
[ 9346.152744] Disabling lock debugging due to kernel taint
[ 9349.585336] NVRM: The NVIDIA probe routine was not called for 1 device(s).
[ 9349.585347] NVRM: This can occur when a driver such as nouveau, rivafb,
[ 9349.585350] NVRM: nvidiafb, or rivatv was loaded and obtained ownership of
[ 9349.585354] NVRM: the NVIDIA device(s).
[ 9349.585362] NVRM: Try unloading the conflicting kernel module (and/or
[ 9349.585366] NVRM: reconfigure your kernel without the conflicting
[ 9349.585369] NVRM: driver(s)), then try loading the NVIDIA kernel module
[ 9349.585372] NVRM: again.
[ 9349.585378] NVRM: No NVIDIA graphics adapter probed!
[ 9353.066200] NVRM: The NVIDIA probe routine was not called for 1 device(s).
[ 9353.066210] NVRM: This can occur when a driver such as nouveau, rivafb,
[ 9353.066214] NVRM: nvidiafb, or rivatv was loaded and obtained ownership of
[ 9353.066218] NVRM: the NVIDIA device(s).
[ 9353.066226] NVRM: Try unloading the conflicting kernel module (and/or
[ 9353.066229] NVRM: reconfigure your kernel without the conflicting
[ 9353.066232] NVRM: driver(s)), then try loading the NVIDIA kernel module
[ 9353.066235] NVRM: again.
[ 9353.066241] NVRM: No NVIDIA graphics adapter probed!
[ 9353.626704] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PSC
[ 9353.626730] acpi_call: Call successful: 0x0
[ 9353.631169] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._DSM
[ 9353.631499] acpi_call: Call successful: {0x59, 0x00, 0x00, 0x11}
[ 9353.635138] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PS3
[ 9353.792066] acpi_call: Call successful: 0x0
[ 9353.795463] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PSC
[ 9353.795489] acpi_call: Call successful: 0x3
[ 9354.040365] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PSC
[ 9354.040390] acpi_call: Call successful: 0x3
[ 9354.044388] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PS0
[ 9354.288907] acpi_call: Call successful: 0x0
[ 9354.292422] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PSC
[ 9354.292448] acpi_call: Call successful: 0x0
[ 9357.755825] NVRM: The NVIDIA probe routine was not called for 1 device(s).
[ 9357.755835] NVRM: This can occur when a driver such as nouveau, rivafb,
[ 9357.755839] NVRM: nvidiafb, or rivatv was loaded and obtained ownership of
[ 9357.755843] NVRM: the NVIDIA device(s).
[ 9357.755851] NVRM: Try unloading the conflicting kernel module (and/or
[ 9357.755855] NVRM: reconfigure your kernel without the conflicting
[ 9357.755858] NVRM: driver(s)), then try loading the NVIDIA kernel module
[ 9357.755861] NVRM: again.
[ 9357.755868] NVRM: No NVIDIA graphics adapter probed!
[ 9650.245514] NVRM: The NVIDIA probe routine was not called for 1 device(s).
[ 9650.245524] NVRM: This can occur when a driver such as nouveau, rivafb,
[ 9650.245528] NVRM: nvidiafb, or rivatv was loaded and obtained ownership of
[ 9650.245532] NVRM: the NVIDIA device(s).
[ 9650.245540] NVRM: Try unloading the conflicting kernel module (and/or
[ 9650.245543] NVRM: reconfigure your kernel without the conflicting
[ 9650.245547] NVRM: driver(s)), then try loading the NVIDIA kernel module
[ 9650.245550] NVRM: again.
[ 9650.245556] NVRM: No NVIDIA graphics adapter probed!
[ 9650.739466] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PSC
[ 9650.739495] acpi_call: Call successful: 0x0
[ 9650.745541] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._DSM
[ 9650.745875] acpi_call: Call successful: {0x59, 0x00, 0x00, 0x11}
[ 9650.749343] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PS3
[ 9650.904066] acpi_call: Call successful: 0x0
[ 9650.907580] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PSC
[ 9650.907612] acpi_call: Call successful: 0x3
[ 9683.220470] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PSC
[ 9683.220496] acpi_call: Call successful: 0x3
[ 9683.225107] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PS0
[ 9683.468974] acpi_call: Call successful: 0x0
[ 9683.473170] acpi_call: Calling \_SB.PCI0.P0P4.GFX0._PSC
[ 9683.473196] acpi_call: Call successful: 0x0
[ 9687.215135] NVRM: The NVIDIA probe routine was not called for 1 device(s).
[ 9687.215145] NVRM: This can occur when a driver such as nouveau, rivafb,
[ 9687.215149] NVRM: nvidiafb, or rivatv was loaded and obtained ownership of
[ 9687.215153] NVRM: the NVIDIA device(s).
[ 9687.215161] NVRM: Try unloading the conflicting kernel module (and/or
[ 9687.215165] NVRM: reconfigure your kernel without the conflicting
[ 9687.215168] NVRM: driver(s)), then try loading the NVIDIA kernel module
[ 9687.215172] NVRM: again.
[ 9687.215178] NVRM: No NVIDIA graphics adapter probed!`

**Comment by DrJohn999** [comment]
No difference in behavior after reboot and running ironhide-configuration again.

**Comment by MrMEEE** [comment]
can I get you to run ironhide-bugreport

**Comment by DrJohn999** [comment]
Bugreport was submitted today.

**Comment by csaba2000** [comment]
I had smilar issue so I made modified scripts :
if you would like to try it out :
sudo mv /usr/local/bin/ironhide-enablecard ironhide-enablecard.back #backup original files
sudo mv /usr/local/bin/ironhide-disablecard ironhide-disablecard.back #backup original files
sudo wget http://dl.dropbox.com/u/1536007/ironhide/ironhide-enablecard -O /usr/local/bin/ironhide-enablecard
sudo wget http://dl.dropbox.com/u/1536007/ironhide/ironhide-disablecard -O /usr/local/bin/ironhide-disablecard

Note: script are a bit rough cuz I had no time finish them fully. 
But I'll finish it tomorow. It's good for a quick test thought;)
EDIT: I was too optimistic...
EDIT: thought with this script I can enable nvidia card but can't turn off yet ...
EDIT2: when something starts to work something else stops ...
EDIT3: now everything seems to work and fully finished script
EDIT4: my script is added to ironhide configurations using submitsystem so you want to use it just reconfigure ironhide and select my(csaba) profile;P

**Comment by DrJohn999** [comment]
A follow up on this issue: solved as of 1.0-1~nattyubuntu38, and still solved in 1.0-1~nattyubuntu39.

Thanks!
Dr John

**Comment by markbaas** [comment]
I still experience this issue on nvidia GT 540M on a Acer Timelinex 4830TG

**Comment by markbaas** [comment]
I only have problems with the nvidia driver on boot up, I think this is related to nvidia 
0000:01:00.0: power state changed by ACPI to D0

So on a different power state it confuses the module

**Comment by karsten-burger** [comment]
Hello, I just experienced a similar problem after my system hung and I had to shut off power, and I have a solution which worked for me.

When trying to insert the nividia kernel module, I got error message 
     FATAL: Error inserting nvidia   ....nvidia.ko : No such device

My solution: with the acpi_call package comes an example script test_off.sh to shut off the Nvidia card (I installed it in /usr/local/acpi_call, so script path is /usr/local/acpi_call/src/mkottman-acpi_call-07a2e89/test_off.sh).
I checked which method tested in the script test_off.sh worked for my system (is printed), then copied the script to "test_on.sh", and changed the method suffix e.g. DOFF to DON. 

Now after rebooting the hanging system I used first test_off.sh, then test_on.sh, and I was able to insert the nvidia module:  (ROOT user): "modprobe nvidia". Now I could start the bumblebee application.

Hopes this helps. Karsten

**Comment by csaba2000** [comment]
I did the same with bumblebee conf.
Althought mine is a bit better needs less "hacking".(added as csaba's profile in bumblebee if you want to use it).
Explanation: That error is caused by "wrong" apci calls which don't turn the nvidia card on properly and nvidia driver outputs an error that no device found.
